# Generated by Django 4.0.4 on 2023-04-11 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=64)),
                ('hobby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_hobby', to='hobbies.hobby')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('NE', 'New'), ('MT', 'Mint'), ('LN', 'Used (Like new)'), ('NM', 'Used (Near mint)'), ('EX', 'Used (Excellent)'), ('VG', 'Used (Very good)'), ('GD', 'Used (Good)'), ('LP', 'Used (Lightly played)'), ('PL', 'Used (Played)'), ('PR', 'Used (Poor)'), ('OB', 'Used (Open box)')], max_length=2)),
                ('hobby', models.ManyToManyField(default=[1], related_name='condition_hobby', to='hobbies.hobby')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=32)),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='individual_collections.collection')),
                ('condition', models.ManyToManyField(default=[1], related_name='condition', to='individual_collections.condition')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='hobbies.item')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
