# Generated by Django 4.0.4 on 2023-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(default='new', max_length=64, unique=True),
        ),
    ]
