# Generated by Django 4.0.4 on 2023-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_collections', '0002_alter_condition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
