# Generated by Django 4.0.4 on 2023-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_collections', '0003_alter_condition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('OW', 'Owned'), ('WL', 'Wishlist')], default='OW', max_length=2),
        ),
    ]
