# Generated by Django 4.0.4 on 2023-03-12 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=17)),
                ('link', models.URLField(default='https://google.com', max_length=512)),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='media',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='source',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='retailers',
        ),
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.AddField(
            model_name='listing',
            name='media',
            field=models.ManyToManyField(blank=True, to='items.media'),
        ),
        migrations.AddField(
            model_name='listing',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='items.listingsource'),
        ),
        migrations.AddField(
            model_name='item',
            name='listings',
            field=models.ManyToManyField(blank=True, to='items.listing'),
        ),
    ]
