# Generated by Django 4.0.4 on 2023-03-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_listing_remove_retailer_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='universal_codes',
        ),
        migrations.AddField(
            model_name='hobby',
            name='universal_code_type',
            field=models.CharField(choices=[('SN', 'Set Number'), ('IS', 'ISBN')], default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='universal_code',
            field=models.CharField(default=None, max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='UniversalCode',
        ),
    ]
