# Generated by Django 4.0.4 on 2023-03-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_listings_listing_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='listing_sources',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='media',
        ),
        migrations.AddField(
            model_name='listingsource',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_hobby', to='items.hobby'),
        ),
        migrations.AddField(
            model_name='media',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_item', to='items.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_hobby', to='items.hobby'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='items.listingsource'),
        ),
    ]
