# Generated by Django 4.0.4 on 2023-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_hobby_listing_sources_remove_listing_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsource',
            name='hobby',
        ),
        migrations.AddField(
            model_name='listingsource',
            name='hobby',
            field=models.ManyToManyField(default=1, related_name='listing_hobby', to='items.hobby'),
        ),
    ]
