# Generated by Django 4.0.4 on 2023-04-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_remove_listingsource_hobby_listingsource_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256, unique=True)),
                ('item_count', models.IntegerField(default=1)),
                ('players', models.IntegerField(default=1)),
                ('estimated_time', models.IntegerField(default=20)),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hobby',
            name='type',
            field=models.CharField(choices=[('CD', 'Collectible card'), ('GM', 'Game'), ('BC', 'Basic collection')], default='BC', max_length=2),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='universal_code_type',
            field=models.CharField(choices=[('SN', 'Set Number'), ('IS', 'ISBN'), ('CN', 'Card Number')], default=None, max_length=2),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256, unique=True)),
                ('hobby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variation_hobby', to='items.hobby')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('release_date', models.DateField(null=True)),
                ('format', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_format', to='items.format')),
                ('hobby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_hobby', to='items.hobby')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sets',
            field=models.ManyToManyField(default=1, related_name='item_set', to='items.set'),
        ),
        migrations.AddField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(default=1, related_name='item_variation', to='items.variation'),
        ),
    ]
