# Generated by Django 4.0.4 on 2023-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_format_hobby_type_alter_hobby_universal_code_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sets',
            field=models.ManyToManyField(default=[1], related_name='item_set', to='items.set'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(default=[1], related_name='item_variation', to='items.variation'),
        ),
        migrations.AlterField(
            model_name='listingsource',
            name='hobby',
            field=models.ManyToManyField(default=[1], related_name='listing_hobby', to='items.hobby'),
        ),
    ]
