# Generated by Django 4.0.4 on 2023-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_sets_alter_item_variations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sets',
            field=models.ManyToManyField(blank=True, default=[1], related_name='item_set', to='items.set'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(blank=True, default=[1], related_name='item_variation', to='items.variation'),
        ),
    ]
