# Generated by Django 4.0.4 on 2023-04-11 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='format',
            name='players',
        ),
        migrations.AddField(
            model_name='format',
            name='average_time',
            field=models.IntegerField(default=20, verbose_name='Average Game Time (minutes)'),
        ),
        migrations.AddField(
            model_name='format',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='format_hobby', to='hobbies.hobby'),
        ),
        migrations.AddField(
            model_name='format',
            name='players_max',
            field=models.IntegerField(default=1, verbose_name='Minimum # of Players'),
        ),
        migrations.AddField(
            model_name='format',
            name='players_min',
            field=models.IntegerField(default=1, verbose_name='Maximum # of Players'),
        ),
    ]
