# Generated by Django 4.0.4 on 2023-04-24 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobbies', '0002_remove_format_estimated_time_remove_format_players_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingSource',
            new_name='Marketplace',
        ),
        migrations.CreateModel(
            name='ItemExternalSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.item')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.marketplace')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
