# Generated by Django 4.0.4 on 2023-03-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
