# Generated by Django 4.0.4 on 2023-04-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_format_hobby_type_alter_hobby_universal_code_type_and_more'),
        ('collection_groups', '0003_alter_collection_hobby_alter_collection_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='condition',
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('NE', 'New'), ('MT', 'Mint'), ('LN', 'Used (Like new)'), ('NM', 'Used (Near mint)'), ('EX', 'Used (Excellent)'), ('VG', 'Used (Very good)'), ('GD', 'Used (Good)'), ('LP', 'Used (Lightly played)'), ('PL', 'Used (Played)'), ('PR', 'Used (Poor)'), ('OB', 'Used (Open box)')], max_length=2)),
                ('hobby', models.ManyToManyField(default=1, related_name='condition_hobby', to='items.hobby')),
                ('last_updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='condition',
            field=models.ManyToManyField(default=1, related_name='condition', to='collection_groups.condition'),
        ),
    ]
